In [1]:
import jax
import jax.numpy as jnp
print("Using jax", jax.__version__)

Using jax 0.4.26


In [6]:
a = jnp.zeros((2, 5), dtype=jnp.float32)
print(a)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:
b = jnp.arange(6)
print(b)

[0 1 2 3 4 5]


In [8]:
b.__class__

jaxlib.xla_extension.ArrayImpl

In [10]:
b.devices()

{CpuDevice(id=0)}

In [14]:
b_gpu = jax.device_put(b)
print(f'Device put: {b_gpu.__class__} on {b_gpu.devices()}')
b_gpu

Device put: <class 'jaxlib.xla_extension.ArrayImpl'> on {CpuDevice(id=0)}


Array([0, 1, 2, 3, 4, 5], dtype=int32)