In [2]:
import torch
import torch.distributions as dist
import matplotlib.pyplot as plt

In [17]:
a=torch.arange(0,9)
print(a.shape)
b=torch.reshape(a,(3,3))
print(a,b)
b.add_(1)
print(a,b)

torch.Size([9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [15]:
x = torch.randn(4, 4)
x.size()
y = x.view(16)
print(id(x),id(y))
print(x,y)
y.add_(1)
print(y)
print(x)


123869271533824 123869276329360
tensor([[-0.2731,  0.6842,  0.4001,  1.3177],
        [ 0.9842, -0.3593,  0.9068, -1.1487],
        [ 1.2145,  0.1246, -1.1406,  0.3142],
        [ 2.0485,  0.3520, -0.8422, -0.0529]]) tensor([-0.2731,  0.6842,  0.4001,  1.3177,  0.9842, -0.3593,  0.9068, -1.1487,
         1.2145,  0.1246, -1.1406,  0.3142,  2.0485,  0.3520, -0.8422, -0.0529])
tensor([ 0.7269,  1.6842,  1.4001,  2.3177,  1.9842,  0.6407,  1.9068, -0.1487,
         2.2145,  1.1246, -0.1406,  1.3142,  3.0485,  1.3520,  0.1578,  0.9471])
tensor([[ 0.7269,  1.6842,  1.4001,  2.3177],
        [ 1.9842,  0.6407,  1.9068, -0.1487],
        [ 2.2145,  1.1246, -0.1406,  1.3142],
        [ 3.0485,  1.3520,  0.1578,  0.9471]])


In [21]:
'''
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
'''
n=torch.arange(9).view((3,3)).T
n

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [24]:
a=torch.arange(5)
b=torch.cat((a,a,a))
b

tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [25]:
import torch

# Define the tensor 'a'
a = torch.arange(5)

# Specify the number of times you want to repeat 'a'
num_repeats = 4

# Repeat 'a' an arbitrary number of times
b = a.repeat(num_repeats)

print(b)

tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])
