In [2]:
import torch
import torch.distributions as dist
import matplotlib.pyplot as plt

In [17]:
a=torch.arange(0,9)
print(a.shape)
b=torch.reshape(a,(3,3))
print(a,b)
b.add_(1)
print(a,b)

torch.Size([9])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]) tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [15]:
x = torch.randn(4, 4)
x.size()
y = x.view(16)
print(id(x),id(y))
print(x,y)
y.add_(1)
print(y)
print(x)


123869271533824 123869276329360
tensor([[-0.2731,  0.6842,  0.4001,  1.3177],
        [ 0.9842, -0.3593,  0.9068, -1.1487],
        [ 1.2145,  0.1246, -1.1406,  0.3142],
        [ 2.0485,  0.3520, -0.8422, -0.0529]]) tensor([-0.2731,  0.6842,  0.4001,  1.3177,  0.9842, -0.3593,  0.9068, -1.1487,
         1.2145,  0.1246, -1.1406,  0.3142,  2.0485,  0.3520, -0.8422, -0.0529])
tensor([ 0.7269,  1.6842,  1.4001,  2.3177,  1.9842,  0.6407,  1.9068, -0.1487,
         2.2145,  1.1246, -0.1406,  1.3142,  3.0485,  1.3520,  0.1578,  0.9471])
tensor([[ 0.7269,  1.6842,  1.4001,  2.3177],
        [ 1.9842,  0.6407,  1.9068, -0.1487],
        [ 2.2145,  1.1246, -0.1406,  1.3142],
        [ 3.0485,  1.3520,  0.1578,  0.9471]])


In [21]:
'''
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
'''
n=torch.arange(9).view((3,3)).T
n

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [24]:
a=torch.arange(5)
b=torch.cat((a,a,a))
b

tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [27]:
import torch

# Define the tensor 'a'
a = torch.arange(5)

# Specify the number of times you want to repeat 'a'
num_repeats = 4

# Repeat 'a' an arbitrary number of times
b = a.repeat(num_repeats)

print(b)

c=a.repeat(4,1)
c

tensor([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])


tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

In [29]:
import torch

def symmetric_matrix(size):
    # Generate a random matrix
    matrix = torch.randn(size, size)
    # Make it symmetric by averaging it with its transpose
    symmetric = (matrix + matrix.t()) / 2
    return symmetric

symmetric_matrix(5)

tensor([[ 0.2208, -0.5079,  0.1171, -0.8050, -0.7198],
        [-0.5079, -0.4351,  0.3247, -0.5068, -0.5457],
        [ 0.1171,  0.3247, -1.6917,  0.0244, -0.5337],
        [-0.8050, -0.5068,  0.0244, -1.1162,  0.6678],
        [-0.7198, -0.5457, -0.5337,  0.6678,  0.0862]])

In [33]:
import torch

matrix = torch.diag(torch.ones(4)) - 2 * torch.eye(4)
print(torch.diag(torch.ones(4)))
print(torch.eye(4))
print(matrix)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[-1.,  0.,  0.,  0.],
        [ 0., -1.,  0.,  0.],
        [ 0.,  0., -1.,  0.],
        [ 0.,  0.,  0., -1.]])


In [43]:
my_mat=torch.diag(-2*torch.ones(3),-1)+torch.diag(torch.ones(4),0)+torch.diag(-2*torch.ones(3),1)
print(my_mat)

tensor([[ 1., -2.,  0.,  0.],
        [-2.,  1., -2.,  0.],
        [ 0., -2.,  1., -2.],
        [ 0.,  0., -2.,  1.]])


In [40]:
torch.diag(torch.ones(4),0)
torch.diag(-2*torch.ones(4),-1)

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [-2.,  0.,  0.,  0.,  0.],
        [ 0., -2.,  0.,  0.,  0.],
        [ 0.,  0., -2.,  0.,  0.],
        [ 0.,  0.,  0., -2.,  0.]])